swagger: '2.0'
tags: 
  - name: API Cleaning Text in File
get:
  description: None
responses:
    '200':
      description: Successful Response
    '400':
      description: Successful Response
    '500':
      description: Successful Response
parameters:
  - name: file
    in: formData
    type: file
    required: false